base_url = "https://kibertexnik.uz"

default_language = "en"
title = "Kibertexnik"
description = "The most difficult thing is to create simply."

# highlight_code = true
compile_sass = true
# generate_rss = true
build_search_index = true

taxonomies = [
  { name = "categories", rss = true },
  { name = "tags", rss = true },
]


[extra]
author = "Kibertexnik Team"
year = "2025"

keywords = "kibertexnik, low-level, iot, embedded"
theme_color = "#000084"
zola386_menu = [
  { path = "", name = "Home" },
  { path = "categories", name = "Categories" },
  { path = "tags", name = "Tags" },
  { path = "about", name = "About" },
]

### SOCIAL MEDIA
image = "https://kibertexnik.uz/images/og.png"
github_user = "kibertexnik"

### I18N WORDS
label_tags = "Tags"
label_tag = "Tag"
label_categories = "Categories"
label_category = "Category"
label_author = "Author"
label_date = "Date"
label_taxonomy = "Taxonomy"
label_reading = "Reading time"
label_read_more = "Read more"
